In [7]:
import numpy as np
import pandas as pd

In [8]:
df=pd.read_csv("input_data/100Z_ld.csv")

df

    energy            ld        errors
0    0.141      1.275586      0.411610
1    0.441      5.571701      1.282614
2    0.741      5.242296      1.481033
3    1.041      8.600554      2.245602
4    1.341      9.554566      3.687864
5    1.641      6.210162      3.222799
6    1.941     32.713905      9.261292
7    2.241     46.852043     14.386389
8    2.541     67.415955     23.482069
9    2.841     93.663757     35.175781
10   3.141    145.085300     66.702278
11   3.441    203.041340    104.239870
12   3.741    258.913420    112.490930
13   4.041    141.691960     84.880257
14   4.341    334.139250    166.022030
15   4.641    552.314030    285.950620
16   5.241   1099.801500    972.362120
17   5.541   3350.669200   1871.523600
18   5.841   2416.959200   1811.908700
19   6.141   6172.837400   4600.695800
20   6.741  33562.598000  28680.588000

In [14]:
df_sel = df.iloc[1:4].copy()

df_sel

   energy        ld    errors
1   0.441  5.571701  1.282614
2   0.741  5.242296  1.481033
3   1.041  8.600554  2.245602

In [18]:
df_sel['left']= (-1/df_sel['energy'])*np.log((df_sel['ld']-df_sel['errors'])/df_sel['ld'])
df_sel['right']= (-1/df_sel['energy'])*np.log((df_sel['ld']+df_sel['errors'])/df_sel['ld'])


df_sel['average']= (df_sel['left']+np.abs(df_sel['right']))/2
df_sel

   energy        ld    errors      left     right   average
1   0.441  5.571701  1.282614  0.593257 -0.469791  0.531524
2   0.741  5.242296  1.481033  0.448050 -0.335795  0.391922
3   1.041  8.600554  2.245602  0.290675 -0.222847  0.256761

In [22]:
aveage_sigma = result = np.sqrt(1/(1/df_sel['average'] ** 2).sum())

print('aveage_sigma',aveage_sigma)
print('aveage_sigma^2',aveage_sigma**2)

aveage_sigma 0.199132207931064
aveage_sigma^2 0.039653636235500514